Nunjucks engine support added
WarmSaluters/mailmerge-js pull request #11
Opened 2024-06-13 05:52 UTC by monikkacha

### Changes 
- Nunjucks engine added 
- README.md updated 
- `--renderer nunjucks` flag added

2024-06-13 06:14 UTC, charlesyu108 requested changes
One small change, but otherwise great job @monikkacha! Pulled it in and looks nice. Thanks for getting this thru, this is awesome 💯 💯 

Once you make the fixes and we merge it in, I can push a publish a new release.

2024-06-13 06:14 UTC, charlesyu108 commented on src/lib/renderers/nunjucks.ts
> +      ),
Let's just make this `{{ subject }}` for simplicity

2024-06-13 07:19 UTC, monikkacha commented on src/lib/renderers/nunjucks.ts
> +      ),
resolved

2024-06-13 21:16 UTC, charlesyu108 commented on src/lib/renderers/nunjucks.ts
> +      ),
Sorry, i was not clear. I meant let's just have the subject be simply `{{ subject }}` with no "Hello,"

2024-06-14 02:56 UTC, monikkacha commented on src/lib/renderers/nunjucks.ts
> +      ),
Hello, Removed .

2024-06-14 17:59 UTC, charlesyu108 approved these changes

2024-06-14 18:00 UTC, merged